// <auto-generated />
using System;
using EgyptianEscape.Domain.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EgyptianEscape.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20230929081445_SeedingVillaTable")]
    partial class SeedingVillaTable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("EgyptianEscape.Domain.Entities.Villa", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Area")
                        .HasColumnType("int");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Occupancy")
                        .HasColumnType("int");

                    b.Property<double>("Price")
                        .HasColumnType("float");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Villa");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Area = 500,
                            Description = "Villa 1 Description",
                            ImageUrl = "https://placehold.co/600x400",
                            Name = "Royal Villa ",
                            Occupancy = 4,
                            Price = 200.0
                        },
                        new
                        {
                            Id = 2,
                            Area = 7000,
                            Description = "Villa 1 Description",
                            ImageUrl = "https://placehold.co/600x400",
                            Name = "Premium Pool Villa ",
                            Occupancy = 5,
                            Price = 300.0
                        },
                        new
                        {
                            Id = 3,
                            Area = 1000,
                            Description = "Villa 1 Description",
                            ImageUrl = "https://placehold.co/600x400",
                            Name = "Luxury Pool Villa ",
                            Occupancy = 6,
                            Price = 400.0
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
